### PR TITLE
Fix comments after named color regression

### LINKED ISSUE #2802: Named color parsing regression in 2.6.0
```
.makeButton(@padding, @background) {
  padding: @padding;
  background: @background;
}

.button {
  .makeButton(
    @padding: 5px, /* Comment */
    @background: black /* Comment */
  );
}
```

The line 9, `@background: black /* Comment */` will error with: `expected ')' got '/'`

However these are fine:

```
.button {
  .makeButton(
    @padding: 5px, /* Comment */
    @background: black); /* Comment */
}
```

```
.button {
  .makeButton(
    @padding: 5px, /* Comment */
    @background: black
  );
}
```

```
.button {
  .makeButton(
    @background: black, /* Comment */
    @padding: 5px /* Comment */
  );
}
```

This is using `less.js 2.6.0` on `node 4.2.6`.

### PR DESCRIPTION
**Pull request by seven-phases-max**
Fixes #2802.

### CODE REVIEW

File: lib/less/parser/parser.js [hunk 1]
```diff
@@ -511,8 +491,24 @@ var Parser = function Parser(context, imports, fileInfo) {
                         }
                         return new(tree.Color)(rgb[1], undefined, '#' + colorCandidateString);
                     }
+                },
 
-                    return this.namedColor();
+                colorKeyword: function () {
```
Comment (seven-phases-max) [inline lib/less/parser/parser.js]: I did not put `colorKeyword()` into `color()` (like it was in colorKeyword) because that way the function is called approximately twice more often (for no real reason).
(Obviously that way it works only because `keyword()` handles named colors in all other contexts, so eventually that will need some refactoring anyway). #2775.

**Comment by matthew-dean** [comment]
Should we do a release with this? How significant is it?

**Comment by seven-phases-max** [comment]
https://github.com/less/less-docs/issues/394#issuecomment-181083285. Unless @SomMeri says she is not expecting any (maybe partial) fix for #2798 soon...

**Comment by SomMeri** [comment]
@matthew-dean @seven-phases-max I did not gave up on it :).
